default:
  model:
    "*object": experimart.models.torch.unet.UNET
    in_channels: 3
    out_channels: ${num_classes}
  model_parameters: 
    "*object": experimart.interoperability.torch.io.get_model_parameters
    model: ${model}
  criterion:
    "*object": torch.nn.CrossEntropyLoss
    ignore_index: 0
  optimizer:
    '*object': torch.optim.Adam
    params: ${model_parameters}
    lr: ${learning_rate}
  scheduler:
    '*object': torch.optim.lr_scheduler.ExponentialLR
    optimizer: ${optimizer}
    gamma: 0.9
  step_components:
    "*object": experimart.interoperability.torch.step.TorchStepComponents
    optimizer: ${optimizer}
    criterion: ${criterion}
    scheduler: ${scheduler}
  training_step_iterator:
    "*object": experimart.interoperability.torch.step.TorchTrainingStepIterator
    model: ${model}
    data_iterator: ${training_data_iterator}
    num_steps: ${num_training_steps}
    components: ${step_components}
    metrics: None
  validation_step_iterator:
    "*object": experimart.interoperability.torch.step.TorchValidationStepIterator
    model: ${model}
    data_iterator: ${validation_data_iterator}
    num_steps: ${num_validation_steps}
    components: ${step_components}
    metrics: None
  trackers:
    torch_model_tracker: 
      "*object": experimart.interoperability.torch.io.TorchModelTracker
      model: ${model}
      output_folder: ${log_path}
      suffix: ${model_name}