default:
  # Project
  project: experimart
  log_path: ./

  # Model
  model_name: model_name
  learning_rate: 0.05
  num_classes: 4
  model: None

  # Data
  training_data_iterator: None
  validation_data_iterator: None

  # Steps
  num_training_steps: 5
  num_validation_steps: 5
  training_step_iterator:
    "*object": experimart.training.step.StepIterator
    model: ${model}
    data_iterator: ${training_data_iterator}
    num_steps: ${num_training_steps}
  validation_step_iterator:
    "*object": experimart.training.step.StepIterator
    model: ${model}
    data_iterator: ${validation_data_iterator}
    num_steps: ${num_validation_steps}

  # Epochs
  num_epochs: 10
  metrics:
    training: 
      'loss': ${$statistics.mean}
    validation: 
      'loss': ${$statistics.mean}
  trackers:
    local_tracker:
      "*object": experimart.monitoring.tracking.LocalTracker
      log_path: ${log_path}
  epoch_callbacks@replace(false): 
    - "*object": experimart.monitoring.monitor.PerformanceMonitor
      metrics: ${metrics}
      trackers: ${trackers}
  epoch_iterator:
    "*object": experimart.training.epoch.EpochIterator
    num_epochs: ${num_epochs}
    training_step_iterator: ${training_step_iterator}
    validation_step_iterator: ${validation_step_iterator}
    epoch_callbacks: ${epoch_callbacks}

