default:

  # Project
  project: experimart
  log_path: ./
  tracker:
    "*object": experimart.monitoring.tracking.Tracker
    log_path: ${log_path}

  # Model
  model_name: model_name
  learning_rate: 0.05
  num_classes: 4
  model: None

  # Data
  training_data_iterator: None
  validation_data_iterator: None

  # Steps
  num_training_steps: 50
  num_validation_steps: 50
  training_step_iterator:
    "*object": experimart.training.step.StepIterator
    model: ${model}
    data_iterator: ${training_data_iterator}
    num_steps: ${num_training_steps}
  validation_step_iterator:
    "*object": experimart.training.step.StepIterator
    model: ${model}
    data_iterator: ${validation_data_iterator}
    num_steps: ${num_validation_steps}

  # Epochs
  num_epochs: 10
  epoch_callbacks@replace(false): 
    - "*object": experimart.monitoring.metrics.MetricSummary
      tracker: ${tracker}
      metrics:
        training: 
          'loss': ${$statistics.mean}
        validation: 
          'loss': ${$statistics.mean}
  epoch_iterator:
    "*object": experimart.training.epoch.EpochIterator
    num_epochs: ${num_epochs}
    training_step_iterator: ${training_step_iterator}
    validation_step_iterator: ${validation_step_iterator}
    epoch_callbacks: ${epoch_callbacks}

