default:

  # Project
  project: None
  log_path: None
  tracker: None

  # Model
  model: None
  learning_rate: 0.05
  num_classes: 4
  
  # Data
  training_data_iterator: None
  validation_data_iterator: None

  # Steps
  num_training_steps: 50
  num_validation_steps: 50
  training_step_iterator:
    "*object": experimart.training.step.StepIterator
    model: ${model}
    data_iterator: ${training_data_iterator}
    num_steps: ${num_training_steps}
  validation_step_iterator:
    "*object": experimart.training.step.StepIterator
    model: ${model}
    data_iterator: ${validation_data_iterator}
    num_steps: ${num_validation_steps}

  # Epochs
  num_epochs: 10
  epoch_callbacks: 
    - "*object": experimart.monitoring.metrics.MetricSummary
      train_callables: 
        'loss': ${$statistics.mean}
      validation_callables: 
        'loss': ${$statistics.mean}
      tracker: ${tracker}
  epoch_iterator:
    "*object": experimart.training.epoch.EpochIterator
    num_epochs: ${num_epochs}
    training_step_iterator: ${training_step_iterator}
    validation_step_iterator: ${validation_step_iterator}
    epoch_callbacks: ${epoch_callbacks}

